---

- name: Ensure installation directory exists
  ansible.builtin.file:
    path: "{{ k3s_install_dir }}"
    state: directory
    mode: 0755

- name: Copy local k3s binary to target host
  ansible.builtin.copy:
    src: k3s
    # TODO: allow airgap to bypass version post-fix
    dest: "{{ k3s_install_dir }}/k3s-{{ k3s_release_version }}"
    mode: 0755
  become: "{{ k3s_become_for_install_dir | ternary(true, false, k3s_become_for_all)  }}"
