---

- import_tasks: ensure_preconfigure_k3s.yml

- import_tasks: ensure_drain_and_remove_nodes.yml

- import_tasks: teardown/uninstall-k3s.yml

- import_tasks: validate/state/uninstalled.yml
  when: not k3s_skip_validation
